replicaCount: 10

hpa:
  minReplicas: 10
  maxReplicas: 12
  cpu: 160
  memory: 160

image:
  repository: nexuscoe.rjil.ril.com:5115/jioent/health/event-publisher-platform #nginx
  tag: prod-latest #stable
  pullPolicy: Always #IfNotPresent
  customTCPPort: 5000
  env:
    - name: EVENT_BROKER_SERVERS
      # value: guru-kafka-6-cp-kafka-headless.guru-queues-6.svc.cluster.local:9092 #localhost:9092
      value: 10.161.38.16:6667,10.161.38.17:6667,10.161.38.18:6667
    - name: EVENT_TOPIC_NAME
      value: event-topic
    - name: EVENT_BROKER_KAFKA_PARTITIONS
      value: "15"
    - name: EVENT_BROKER_KAFKA_REPLICATION_FACTOR
      value: "3"
    - name: EVENT_TOPIC_CLEANUP_POLICY
      value: delete
    - name: EVENT_TOPIC_RETENTION_MS
      value: "3600000" # 1 hour
    - name: LAB_EVENT_TOPIC_NAME
      value: lab-topic
    - name: LAB_EVENT_BROKER_KAFKA_PARTITIONS
      value: "15"
    - name: LAB_EVENT_BROKER_KAFKA_REPLICATION_FACTOR
      value: "3"
    - name: LAB_EVENT_TOPIC_CLEANUP_POLICY
      value: delete
    - name: LAB_EVENT_TOPIC_RETENTION_MS
      value: "25200000" # 7 hours
    - name: LOGGING_LEVEL
      value: WARN


imagePullSecrets: #[]
  - name: nexus-container-repo
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 1000m
    memory: 512Mi
  requests:
    cpu: 500m
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}

# dockerImageCredentials:
#   registry: guruartifacts.azurecr.io
#   username: guruartifacts
#   password: zo8sAObBAq/Q9iEMa+TAR42=Ly8yYytp
