{{ if .Values.app.configFiles }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "guruchart.fullname" . }}
  labels:
{{ include "guruchart.labels" . | indent 4 }}
data:
{{- range $config := .Values.app.configFiles }}
  {{ $config.fileName }}: {{ $config.data | toYaml | indent 4 }}
{{- end }}
{{ end }}
