{{ if .Values.hpa.minReplicas}}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "guruchart.fullname" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "guruchart.fullname" . }}
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      {{ if .Values.hpa.cpu }}
      targetAverageUtilization: {{ .Values.hpa.cpu }}
      {{ else }}
      targetAverageUtilization: 80
      {{ end }}

  - type: Resource
    resource:
      name: memory
      {{ if .Values.hpa.memory}}
      targetAverageUtilization: {{ .Values.hpa.memory }}
      {{ else }}
      targetAverageUtilization: 80
      {{ end }}
{{ end }}