apiVersion: v1
kind: Service
metadata:
  name: {{ include "guruchart.fullname" . }}
  labels:
{{ include "guruchart.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  {{ if .Values.service.loadBalancerIP}}
  loadBalancerIP: {{ .Values.service.loadBalancerIP}}
  {{ end }}
  {{ if .Values.service.externalTrafficPolicy}}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy}}
  {{ end }}
  selector:
    app.kubernetes.io/name: {{ include "guruchart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
