{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "guruchart.serviceAccountName" . }}
  labels:
{{ include "guruchart.labels" . | indent 4 }}
{{- end -}}
